(self.shader 'fragment "shader/staticmesh.frag")
(self.shader 'vertex "shader/staticmesh.vert")
(self.mesh "mesh/rock_1.obj")
(self.texture 'tex "texture/rocks.png?comp=bc1")
(self.texture 'mat_tex "texture/default_mat.png")
