(self.shader 'fragment "shader/staticmesh.frag")
(self.shader 'vertex "shader/staticmesh.vert")
(self.mesh "mesh/spaceship.obj")
(self.texture 'tex "texture/spaceship.png?comp=bc1")
(self.texture 'mat_tex "texture/spaceship_mat.png")
