(self.shader 'fragment "shader/staticmesh.frag")
(self.shader 'vertex "shader/staticmesh.vert")
(self.cull_mode 'none)
(self.mesh "mesh/thruster_fire.obj")
(self.texture 'tex "texture/thruster_fire.png?comp=bc3")
(self.texture 'mat_tex "texture/default_mat.png")
